#!/bin/bash

# Put the current working directory path here:
workdir="${HOME}/WholeGenomesPractical/"

# Put the location of the geno_qc.[bed|bim|fam] files here:
datadir="${HOME}/pract9_WholeGenomes/data/"
